name: iHelp
favicon: null
layout_spectrum: 0.6797649590298533
typography_spectrum: 0.403654218185693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8296946194022894
  lightness: 0.2666319061536342
  saturation: 0.3295456620398909
  rhythmicContrast: 0.7528853372205049
purpose: []
